services:
  kubo:
    image: ipfs/kubo:master-latest
    volumes:
      - ipfs_path:/data/ipfs
      - ipfs_fuse:/ipfs
      - ipns_fuse:/ipns
      - ./config/kubo/0001-init-config.sh:/container-init.d/0001-init-config.sh
    environment:
      - IPFS_PATH=/data/ipfs
      - IPFS_PROFILE=server
    ports:
      - ${KUBO_TCP_PORT:-4001}:4001/tcp
      - ${KUBO_UDP_PORT:-4001}:4001/udp
      - ${KUBO_ADMIN_PORT:-5001}:5001
      - ${KUBO_GATEWAY_PORT:-1882}:8080
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  ipfs_path:
  ipfs_fuse:
  ipns_fuse:
