version: "3.8"
name: nftcdn

services:
  postgres:
    image: postgres:16.1-alpine
    profiles: ["mainnet", "preprod", "preview"]
    env_file: ./.env
    environment:
      - POSTGRES_LOGGING=true
    ports:
      - 127.0.0.1:5432:5432
    shm_size: '2gb'
    volumes:
      - ./config/postgresql/postgresql.conf:/etc/postgresql.conf
      - ./config/postgresql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - postgres-data:/var/lib/postgresql/data
    command: [
      "-c", "config_file=/etc/postgresql.conf"
    ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  kubo:
    image: ipfs/kubo:master-latest
    profiles: ["mainnet", "preprod", "preview"]
    volumes:
      - ipfs_path:/data/ipfs
      - ipfs_fuse:/ipfs
      - ipns_fuse:/ipns
      - ./config/kubo/0001-init-config.sh:/container-init.d/0001-init-config.sh
    environment:
      - IPFS_PATH=/data/ipfs
      - IPFS_PROFILE=server
    ports:
      - 4001:4001/tcp
      - 4001:4001/udp
      - 127.0.0.1:5001:5001
      - 127.0.0.1:1882:8080
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  haproxy:
    image: haproxy:2.8.3
    profiles: ["mainnet", "preprod", "preview"]
    env_file: ./.env
    ports:
      - 80:8080
      - 443:8443
    shm_size: '2gb'
    volumes:
      - ./config/haproxy:/usr/local/etc/haproxy
      - /etc/ssl/ssl_key.pem:/ssl_key.pem
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

# MAINNET STACK ####################################################################################

  cardano-node-ogmios-mainnet:
    image: cardanosolutions/cardano-node-ogmios:v6.1.0_8.7.3-mainnet
    profiles: ["mainnet"]
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    ports:
      - 127.0.0.1:1337:1337
      - 3000:3000
    restart: on-failure
    volumes:
      - node-db-mainnet:/db
      - node-ipc-mainnet:/ipc

  nftcdn-extractor-mainnet:
    profiles: ["mainnet"]
    build:
      context: .
      target: nftcdn-extractor
    env_file: ./.env
    volumes:
      - cache-mainnet:/home/node/app/cache
    environment:
      - NETWORK=mainnet
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=nftcdn_mainnet
      - OGMIOS_HOST=cardano-node-ogmios-mainnet
      - OGMIOS_PORT=1337
    depends_on:
      - cardano-node-ogmios-mainnet
      - postgres
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  nftcdn-server-mainnet:
    profiles: ["mainnet"]
    build:
      context: .
      target: nftcdn-server
    env_file: ./.env
    environment:
      - NETWORK=mainnet
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=nftcdn_mainnet
      - KUBO_HOST=kubo
      - KUBO_PORT=8080
      - MAX_IMAGE_SIZE=2048
      - SERVER_IMAGE_URL=
    volumes:
      - cache-mainnet:/home/node/app/cache
    ports:
      - 127.0.0.1:4700:4700
    depends_on:
      - nftcdn-extractor-mainnet
      - kubo
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

# PREPROD STACK ####################################################################################

  cardano-node-ogmios-preprod:
    image: cardanosolutions/cardano-node-ogmios:v6.1.0_8.7.3-preprod
    profiles: ["preprod"]
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    ports:
      - 127.0.0.1:1338:1337
      - 3001:3000
    restart: on-failure
    volumes:
      - node-db-preprod:/db
      - node-ipc-preprod:/ipc

  nftcdn-extractor-preprod:
    profiles: ["preprod"]
    build:
      context: .
      target: nftcdn-extractor
    env_file: ./.env
    volumes:
      - cache-preprod:/home/node/app/cache
    environment:
      - NETWORK=preprod
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=nftcdn_preprod
      - OGMIOS_HOST=cardano-node-ogmios-preprod
      - OGMIOS_PORT=1337
    depends_on:
      - cardano-node-ogmios-preprod
      - postgres
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  nftcdn-server-preprod:
    profiles: ["preprod"]
    build:
      context: .
      target: nftcdn-server
    env_file: ./.env
    environment:
      - NETWORK=preprod
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=nftcdn_preprod
      - KUBO_HOST=kubo
      - KUBO_PORT=8080
      - MAX_IMAGE_SIZE=2048
      - SERVER_IMAGE_URL=
    volumes:
      - cache-preprod:/home/node/app/cache
    ports:
      - 127.0.0.1:4701:4700
    depends_on:
      - nftcdn-extractor-preprod
      - kubo
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

# PREVIEW STACK ####################################################################################


  cardano-node-ogmios-preview:
    image: cardanosolutions/cardano-node-ogmios:v6.1.0_8.7.3-preview
    profiles: ["preview"]
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    ports:
      - 127.0.0.1:1339:1337
      - 3002:3000
    restart: on-failure
    volumes:
      - node-db-preview:/db
      - node-ipc-preview:/ipc

  nftcdn-extractor-preview:
    profiles: ["preview"]
    build:
      context: .
      target: nftcdn-extractor
    env_file: ./.env
    volumes:
      - cache-preview:/home/node/app/cache
    environment:
      - NETWORK=preview
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=nftcdn_preview
      - OGMIOS_HOST=cardano-node-ogmios-preview
      - OGMIOS_PORT=1337
    depends_on:
      - cardano-node-ogmios-preview
      - postgres
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  nftcdn-server-preview:
    profiles: ["preview"]
    build:
      context: .
      target: nftcdn-server
    env_file: ./.env
    environment:
      - NETWORK=preview
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=nftcdn_preview
      - KUBO_HOST=kubo
      - KUBO_PORT=8080
      - MAX_IMAGE_SIZE=2048
      - SERVER_IMAGE_URL=
    volumes:
      - cache-preview:/home/node/app/cache
    ports:
      - 127.0.0.1:4702:4700
    depends_on:
      - nftcdn-extractor-preview
      - kubo
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"


volumes:
  ipfs_path:
  ipfs_fuse:
  ipns_fuse:
  postgres-data:
  node-db-mainnet:
  node-db-preprod:
  node-db-preview:
  node-ipc-mainnet:
  node-ipc-preprod:
  node-ipc-preview:
  cache-mainnet:
  cache-preprod:
  cache-preview:
