name: nftcdn

services:
  kubo:
    image: ipfs/kubo:master-latest
    profiles: ["mainnet", "preprod", "preview"]
    volumes:
      - ipfs_path:/data/ipfs
      - ipfs_fuse:/ipfs
      - ipns_fuse:/ipns
      - ./config/kubo/0001-init-config.sh:/container-init.d/0001-init-config.sh
    environment:
      - IPFS_PATH=/data/ipfs
      - IPFS_PROFILE=server
    ports:
      - 4001:4001/tcp
      - 4001:4001/udp
      - 127.0.0.1:5001:5001
      - 127.0.0.1:1882:8080
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  haproxy:
    image: haproxy:2.8.3
    profiles: ["mainnet", "preprod", "preview"]
    env_file: ./.env
    ports:
      - 80:8080
      - 443:8443
    shm_size: '2gb'
    volumes:
      - ./config/haproxy:/usr/local/etc/haproxy
      - /etc/ssl/ssl_key.pem:/ssl_key.pem
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

include:
  - docker-compose.mainnet.yml
  - docker-compose.preprod.yml
  - docker-compose.preview.yml

volumes:
  ipfs_path:
  ipfs_fuse:
  ipns_fuse:
