services:
  kubo:
    image: ipfs/kubo:master-latest
    volumes:
      - ipfs_path:/data/ipfs
      - ipfs_fuse:/ipfs
      - ipns_fuse:/ipns
      - ./config/kubo/0001-init-config.sh:/container-init.d/0001-init-config.sh
    environment:
      - IPFS_PATH=/data/ipfs
      - IPFS_PROFILE=server
    ports:
      - ${KUBO_TCP_PORT:-4001}:4001/tcp
      - ${KUBO_UDP_PORT:-4001}:4001/udp
      - ${KUBO_ADMIN_PORT:-127.0.0.1:5001}:5001
      - ${KUBO_GATEWAY_PORT:-127.0.0.1:1882}:8080
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    labels:
      - traefik.enable=true
      - traefik.http.routers.kubo.rule=Host(`any`) || ((Header(`Host-Resolver`,`kubo/mainnet`) || Header(`Host-Resolver`,`kubo/preprod`) || Header(`Host-Resolver`,`kubo/preview`)) && Header(`Bearer-Resolver`,`${BEARER_RESOLVER_TOKEN}`))
      - traefik.http.routers.kubo.entrypoints=websecure
      - traefik.http.routers.kubo.tls=true
      - traefik.http.routers.kubo.service=kubo
      - traefik.http.services.kubo.loadbalancer.server.port=8080
    networks:
      - default
      - traefik

volumes:
  ipfs_path:
  ipfs_fuse:
  ipns_fuse:

networks:
  traefik:
    external: true
